/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelo.ClienteModelo;
import Controle.ClienteControle;
import DAO.ClienteDAO;
import Utilitarios.Conexao;
import Utilitarios.Corretores;
import Utilitarios.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author bokao
 */
public class ClienteTela extends javax.swing.JFrame {

    MaskFormatter FormatoTel;
    SimpleDateFormat FormatoData;
    Date DataAtual;
    ClienteModelo ClienteB;
    ClienteControle ClienteC;
    ClienteDAO ClienteD;
    DefaultTableModel modelo;
    String situacao;

    public ClienteTela() {
        initComponents();

        FormatoData = new SimpleDateFormat("dd/MM/yyyy");
        DataAtual = new Date();
        //jTextDataNascCli.setEnabled(false);
        ClienteB = new ClienteModelo();
        ClienteC = new ClienteControle();
        ClienteD = new ClienteDAO();

        //modelo = (DefaultTableModel) jTableCliente.getModel();
        preencherTabela("select * from cliente where situacaoCli like 'Ativo'order by endCli ");
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCadCli = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodCLi = new javax.swing.JTextField();
        txtNomeCli = new javax.swing.JTextField();
        txtEndCli = new javax.swing.JTextField();
        txtBairroCli = new javax.swing.JTextField();
        txtnumeroEndCli = new javax.swing.JTextField();
        txtPesquisarCli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jRadioInativar = new javax.swing.JRadioButton();
        try{
            FormatoTel = new MaskFormatter("####-####");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "erro ao inserir campo personalizado", "Erro", 0);
        }
        txtTelResCli = new JFormattedTextField(FormatoTel);
        try{
            FormatoTel = new MaskFormatter("#####-####");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "erro ao inserir campo personalizado", "Erro", 0);
        }
        txtTelCelCli = new JFormattedTextField(FormatoTel);
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);

        jPanelCadCli.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Bairro:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Número:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Telefone Res.:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Celular:");

        txtCodCLi.setEditable(false);
        txtCodCLi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodCLi.setEnabled(false);

        txtNomeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeCli.setEnabled(false);
        txtNomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeCliKeyPressed(evt);
            }
        });

        txtEndCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEndCli.setEnabled(false);
        txtEndCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEndCliKeyPressed(evt);
            }
        });

        txtBairroCli.setEnabled(false);
        txtBairroCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroCliKeyPressed(evt);
            }
        });

        txtnumeroEndCli.setEnabled(false);
        txtnumeroEndCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumeroEndCliKeyPressed(evt);
            }
        });

        txtPesquisarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPesquisarCliMousePressed(evt);
            }
        });
        txtPesquisarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarCliActionPerformed(evt);
            }
        });
        txtPesquisarCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarCliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarCliKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Pesquisar:");

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/addCliente.png"))); // NOI18N
        jButtonNovo.setToolTipText("NOVO");
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jButtonNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNovoKeyPressed(evt);
            }
        });

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/btn_SAlvar.png"))); // NOI18N
        jButtonCadastrar.setToolTipText("CADASTRAR");
        jButtonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrar.setEnabled(false);
        jButtonCadastrar.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jButtonCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCadastrarKeyPressed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/btn_editar.png"))); // NOI18N
        jButtonEditar.setToolTipText("EDITAR");
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setEnabled(false);
        jButtonEditar.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/clean.png"))); // NOI18N
        jButtonCancelar.setToolTipText("CANCELAR");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLayout = new javax.swing.GroupLayout(jPanelButton);
        jPanelButton.setLayout(jPanelButtonLayout);
        jPanelButtonLayout.setHorizontalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanelButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCadastrar, jButtonCancelar, jButtonEditar, jButtonNovo});

        jPanelButtonLayout.setVerticalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLayout.createSequentialGroup()
                .addGroup(jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jRadioInativar.setText("Inativar Cliente");
        jRadioInativar.setEnabled(false);
        jRadioInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioInativarActionPerformed(evt);
            }
        });

        txtTelResCli.setEnabled(false);
        txtTelResCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelResCliKeyPressed(evt);
            }
        });

        txtTelCelCli.setEnabled(false);
        txtTelCelCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelCelCliKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadCliLayout = new javax.swing.GroupLayout(jPanelCadCli);
        jPanelCadCli.setLayout(jPanelCadCliLayout);
        jPanelCadCliLayout.setHorizontalGroup(
            jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadCliLayout.createSequentialGroup()
                        .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelResCli, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtnumeroEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelCelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadCliLayout.createSequentialGroup()
                        .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodCLi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeCli))
                            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(73, 73, 73)))
                        .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jRadioInativar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadCliLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadCliLayout.setVerticalGroup(
            jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCodCLi)
                        .addComponent(jLabel2))
                    .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioInativar)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtnumeroEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(txtTelResCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelCelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CLIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelCadCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanelCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2774, 2774, 2774))
        );

        setSize(new java.awt.Dimension(866, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        try {
            String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("permissaoUsu").equals("Administrador") || (rs.getString("permissaoUsu").equals("Operador"))) {
                    limparCampos();
                    habilitarCampos(true);
                    ClienteC.ControleCodigo();
                    txtCodCLi.setText(ClienteC.ControleCodigo());
                    jButtonNovo.setEnabled(false);
                    jRadioInativar.setEnabled(true);
                    txtNomeCli.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro!!!", 0, new ImageIcon("imagens/btn_users.png"));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro!!!", 0, new ImageIcon("imagens/btn_users.png"));
        }


    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        popularClienteBeans();
        ClienteC.verificardados(ClienteB);
        limparCampos();
        txtPesquisarCli.setText("");
        habilitarCampos(false);
        txtPesquisarCli.setEnabled(true);
        jButtonCadastrar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        txtPesquisarCli.requestFocus();
       preencherTabela("select * from cliente where situacaoCli like 'Ativo'order by endCli");

        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("permissaoUsu").equals("Administrador")) {
                    popularClienteBeans();
                    ClienteC.verificardadosEditar(ClienteB);
                    limparCampos();
                    jButtonEditar.setEnabled(false);
                    jButtonCancelar.setEnabled(false);
                    jButtonNovo.setEnabled(true);
               }
                preencherTabela("select * from cliente where situacaoCli like 'Ativo'order by endCli");
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para editar os campos!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_users.png"));
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void txtPesquisarCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarCliKeyReleased
      
    }//GEN-LAST:event_txtPesquisarCliKeyReleased

    private void txtPesquisarCliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarCliMousePressed
        
    }//GEN-LAST:event_txtPesquisarCliMousePressed

    private void txtNomeCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtEndCli.requestFocus();
        }
    }//GEN-LAST:event_txtNomeCliKeyPressed

    private void txtEndCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtnumeroEndCli.requestFocus();
        }
    }//GEN-LAST:event_txtEndCliKeyPressed

    private void txtBairroCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtTelResCli.requestFocus();
        }
    }//GEN-LAST:event_txtBairroCliKeyPressed

    private void txtnumeroEndCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroEndCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtBairroCli.requestFocus();
        }
    }//GEN-LAST:event_txtnumeroEndCliKeyPressed

    private void txtPesquisarCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (txtPesquisarCli.getText().equals("")) {
                jButtonNovo.requestFocus();
            } else {
                preencherTabela("select * from cliente where endCli like '" + txtPesquisarCli.getText() + "%' and situacaoCli like 'Ativo' order by endCli");
                    
            }
        }
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            dispose();
    }
    }//GEN-LAST:event_txtPesquisarCliKeyPressed

    private void jButtonCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCadastrarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            popularClienteBeans();
            ClienteC.verificardados(ClienteB);
            limparCampos();
            txtPesquisarCli.setText("");
            habilitarCampos(false);
            txtPesquisarCli.setEnabled(true);
            jButtonCadastrar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            txtPesquisarCli.requestFocus();
        }
        preencherTabela("select * from cliente where situacaoCli like 'Ativo'order by endCli");
    }//GEN-LAST:event_jButtonCadastrarKeyPressed

    private void txtPesquisarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarCliActionPerformed
        
            
  
    }//GEN-LAST:event_txtPesquisarCliActionPerformed

    private void jRadioInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioInativarActionPerformed
        try {
            String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("permissaoUsu").equals("Administrador")) {
                    int resposta = 0;
                    resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente Inativar este cliente??");
                    if (resposta == JOptionPane.YES_OPTION) {
                        if (jRadioInativar.isSelected()) {
                            situacao = "Inativo";
                            InativarCliente();
                            //EntrC.InativarEntregador(jRadioInativar.setVisible(true));
                            JOptionPane.showMessageDialog(null, "Cliente Inativado com sucesso!!", "Salvo", 1, new ImageIcon("imagens/ok.png"));
                            limparCampos();
                            jRadioInativar.setEnabled(false);
                            modelo.setNumRows(0);
                            jButtonEditar.setEnabled(false);
                            jButtonCancelar.setEnabled(false);
                            txtPesquisarCli.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Você não tem permissão para editar os campos!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_users.png"));
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para editar os campos!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_users.png"));
        }
    }//GEN-LAST:event_jRadioInativarActionPerformed

    private void jButtonNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNovoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
                PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    if (rs.getString("permissaoUsu").equals("Administrador") || (rs.getString("permissaoUsu").equals("Operador"))) {
                        //ClienteTela telaC = new ClienteTela();
                        //telaC.setVisible(true);
                        limparCampos();
                        habilitarCampos(true);
                        ClienteC.ControleCodigo();
                        txtCodCLi.setText(ClienteC.ControleCodigo());
                        jButtonNovo.setEnabled(false);
                        jRadioInativar.setEnabled(true);
                        txtNomeCli.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_users.png"));
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_users.png"));
            }

        }
    }//GEN-LAST:event_jButtonNovoKeyPressed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        String nomeCliente = "" + jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 2);
        
        ClienteB = ClienteC.ControlePreencherCampos(nomeCliente);
        habilitarCampos(true);
        jButtonCadastrar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        txtCodCLi.setText(ClienteB.getCodigo() + "");
        txtNomeCli.setText(ClienteB.getNome());
        txtEndCli.setText(ClienteB.getEndereco());
        txtnumeroEndCli.setText(ClienteB.getNumero());
        txtBairroCli.setText(ClienteB.getBairro());
        txtTelResCli.setText(ClienteB.getTelefoneResidencial());
        txtTelCelCli.setText(ClienteB.getTelefoneCelular());
        jButtonCancelar.setEnabled(true);

    }//GEN-LAST:event_jTableClienteMouseClicked

    private void txtTelResCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelResCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtTelCelCli.requestFocus();
        }
    }//GEN-LAST:event_txtTelResCliKeyPressed

    private void txtTelCelCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelCelCliKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButtonCadastrar.requestFocus();
        }
    }//GEN-LAST:event_txtTelCelCliKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelCadCli;
    private javax.swing.JRadioButton jRadioInativar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField txtBairroCli;
    private javax.swing.JTextField txtCodCLi;
    private javax.swing.JTextField txtEndCli;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtPesquisarCli;
    private javax.swing.JTextField txtTelCelCli;
    private javax.swing.JTextField txtTelResCli;
    private javax.swing.JTextField txtnumeroEndCli;
    // End of variables declaration//GEN-END:variables

    final void habilitarCampos(boolean valor) {
        txtCodCLi.setEnabled(valor);
        txtNomeCli.setEnabled(valor);
        txtEndCli.setEnabled(valor);
        txtBairroCli.setEnabled(valor);
        txtnumeroEndCli.setEnabled(valor);
        txtTelResCli.setEnabled(valor);
        txtTelCelCli.setEnabled(valor);
        jButtonCadastrar.setEnabled(valor);
        jButtonCancelar.setEnabled(valor);

    }

    final void popularClienteBeans() {
        ClienteB.setNome(txtNomeCli.getText());
        ClienteB.setEndereco(txtEndCli.getText());
        ClienteB.setBairro(txtBairroCli.getText());
        ClienteB.setNumero(txtnumeroEndCli.getText());
        ClienteB.setTelefoneResidencial(txtTelResCli.getText());
        ClienteB.setTelefoneCelular(txtTelCelCli.getText());
    }

    final void limparCampos() {
        txtCodCLi.setText("");
        txtNomeCli.setText("");
        txtBairroCli.setText("");
        txtnumeroEndCli.setText("");
        txtEndCli.setText("");
        txtTelResCli.setText("");
        txtTelCelCli.setText("");
        txtPesquisarCli.setText("");
    }

    public void InativarCliente() {
        try {

            String SQLInsertion = "update cliente set nomeCli = ?, endCli = ?, numeroEnd = ?,bairroCli = ?,telResCli = ?, telCelCli = ?, situacaoCli = ? where codCli = ? ";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(SQLInsertion);
            pst.setString(1, txtNomeCli.getText());
            pst.setString(2, txtEndCli.getText());
            pst.setString(3, txtBairroCli.getText());
            pst.setString(4, txtnumeroEndCli.getText());
            pst.setString(5, "");
            pst.setString(6, "");
            pst.setString(7, situacao);
            pst.setInt(8, Integer.parseInt(txtCodCLi.getText()));

            pst.execute();
            Conexao.getConnection().commit();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            //JOptionPane.showMessageDialog(null, "Erro ao Alterar dados do entregador!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Cód", "Cliente", "Endereço", "Número", "Bairro", "Tel. Res.", "Celular"};

        //String SQL = "select * from cliente where nomeCli like '%" + jtNomeCli.getText() + "%' and situacao like 'Ativo' order by endCli";
        try {
            PreparedStatement pst = Conexao.getConnection().prepareStatement(SQL);
            ResultSet rs = pst.executeQuery();
            rs.next();
            do {
                dados.add(new Object[]{rs.getInt("codCli"), rs.getString("nomeCli"), rs.getString("endCli"), rs.getString("numeroEnd"), rs.getString("bairroCli"), rs.getString("telResCli"), rs.getString("telCelCli")});
            } while (rs.next());

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, ex, "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            //JOptionPane.showMessageDialog(null, "Erro ao preencher Tabela", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableCliente.setModel(modelo);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(240);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTableCliente.getColumnModel().getColumn(4).setResizable(false);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(73);
        jTableCliente.getColumnModel().getColumn(5).setResizable(false);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableCliente.getColumnModel().getColumn(6).setResizable(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);
        jTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

}
