/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelo.FuncionarioModelo;
import Controle.FuncionarioControle;
import DAO.ClienteDAO;
import DAO.FuncionarioDAO;
import Utilitarios.Conexao;
import Utilitarios.Corretores;
import Utilitarios.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author bokao
 */
public class FuncionarioTela extends javax.swing.JFrame {

    MaskFormatter FormatoTel;
    SimpleDateFormat FormatoData;
    Date DataAtual;
    FuncionarioModelo FuncB;
    FuncionarioControle FuncC;
    FuncionarioDAO FuncD;
    String situacao;
    //ClienteDAO ClienteD;
    //DefaultTableModel modelo;
    
    public FuncionarioTela() {
        initComponents();

        FormatoData = new SimpleDateFormat("dd/MM/yyyy");
        DataAtual = new Date();
        FuncC = new FuncionarioControle();
        FuncB = new FuncionarioModelo();
        FuncD = new FuncionarioDAO();
        //ClienteD = new ClienteDAO();
        //modelo = (DefaultTableModel) jTableFuncionario.getModel();

        preencherTabela("select * from funcionario where situacaoFunc like 'Ativo'order by nomeFunc");
        //habilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCadCli = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodFunc = new javax.swing.JTextField();
        txtNomeFunc = new javax.swing.JTextField();
        jtPesquisarFunc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        txtDataCad = new javax.swing.JFormattedTextField();
        cbCargo = new javax.swing.JComboBox<>();
        jRadioInativar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionários");
        setResizable(false);

        jPanelCadCli.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cargo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Data cadastro:");

        txtCodFunc.setEditable(false);
        txtCodFunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodFunc.setEnabled(false);

        txtNomeFunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeFunc.setEnabled(false);
        txtNomeFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFuncKeyPressed(evt);
            }
        });

        jtPesquisarFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtPesquisarFuncMousePressed(evt);
            }
        });
        jtPesquisarFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesquisarFuncKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarFuncKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Pesquisar:");

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/addCliente.png"))); // NOI18N
        jButtonNovo.setToolTipText("NOVO");
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jButtonNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNovoKeyPressed(evt);
            }
        });

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/btn_SAlvar.png"))); // NOI18N
        jButtonCadastrar.setToolTipText("CADASTRAR");
        jButtonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrar.setEnabled(false);
        jButtonCadastrar.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jButtonCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCadastrarKeyPressed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/btn_editar.png"))); // NOI18N
        jButtonEditar.setToolTipText("EDITAR");
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setEnabled(false);
        jButtonEditar.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/clean.png"))); // NOI18N
        jButtonExcluir.setToolTipText("CANCELAR");
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.setMaximumSize(new java.awt.Dimension(72, 60));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLayout = new javax.swing.GroupLayout(jPanelButton);
        jPanelButton.setLayout(jPanelButtonLayout);
        jPanelButtonLayout.setHorizontalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanelButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCadastrar, jButtonEditar, jButtonExcluir, jButtonNovo});

        jPanelButtonLayout.setVerticalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLayout.createSequentialGroup()
                .addGroup(jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        try {
            txtDataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCad.setEnabled(false);

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Função", "Balconista", "Caixa", "Garçom", "Chapeiro", "Auxiliar Cozinha", "Cozinheira", "Faxineira" }));
        cbCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbCargo.setEnabled(false);
        cbCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbCargoKeyPressed(evt);
            }
        });

        jRadioInativar.setText("Inativar Funcionário");
        jRadioInativar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioInativar.setEnabled(false);
        jRadioInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioInativarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadCliLayout = new javax.swing.GroupLayout(jPanelCadCli);
        jPanelCadCli.setLayout(jPanelCadCliLayout);
        jPanelCadCliLayout.setHorizontalGroup(
            jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtPesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataCad, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jRadioInativar))))))
                    .addGroup(jPanelCadCliLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelCadCliLayout.setVerticalGroup(
            jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadCliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCodFunc)
                        .addComponent(jLabel2))
                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDataCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioInativar))
                .addGap(18, 18, 18)
                .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FUNCIONÁRIOS");

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCadCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2743, 2743, 2743))
        );

        setSize(new java.awt.Dimension(653, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        try {
            String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("permissaoUsu").equals("Administrador")) {
                    limparCampos();
                    habilitarCampos(true);
                    FuncC.ControleCodigo();
                    txtCodFunc.setText(FuncC.ControleCodigo());
                    //DataAtual = new Date();
                    //txtDataCad.setText(FormatoData.format(DataAtual));
                    jButtonCadastrar.setEnabled(true);                   
                    jButtonNovo.setEnabled(false);
                    txtNomeFunc.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }


    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        popularFuncionarioModelo();
        FuncC.verificardados(FuncB);
        limparCampos();
        jtPesquisarFunc.setEnabled(true);
        jButtonCadastrar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        txtNomeFunc.setText("");
        txtDataCad.setText("");
        habilitarCampos(false);
        //modelo.setNumRows(0);
        //FuncC.controlePesquisa(jtPesquisarFunc.getText(), modelo);

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("permissaoUsu").equals("Administrador")) {
                    popularFuncionarioModelo();
                    FuncC.verificardadosEditar(FuncB);
                    limparCampos();
                    //modelo.setNumRows(0);
                    habilitarCampos(false);
                    jButtonNovo.setEnabled(true);
                    jButtonEditar.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Você não tem permissão para editar os campos!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para editar os campos!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }


    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        limparCampos();
        txtDataCad.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCadastrar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        cbCargo.setEnabled(false);
        jtPesquisarFunc.requestFocus();

        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jtPesquisarFuncKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarFuncKeyReleased

    }//GEN-LAST:event_jtPesquisarFuncKeyReleased

    private void jTableFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionarioMouseClicked

        String nomeFunc = "" + jTableFuncionario.getValueAt(jTableFuncionario.getSelectedRow(), 1);
        FuncB = FuncC.ControlePreencherCampos(nomeFunc);
        habilitarCampos(true);
        jButtonCadastrar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        txtCodFunc.setText(FuncB.getCodigo() + "");
        txtNomeFunc.setText(FuncB.getNome());
        txtDataCad.setText(FuncB.getDataCadastro());
        cbCargo.setSelectedItem(FuncB.getFuncao());
        jRadioInativar.setEnabled(true);


    }//GEN-LAST:event_jTableFuncionarioMouseClicked

    private void jtPesquisarFuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPesquisarFuncMousePressed
        
    }//GEN-LAST:event_jtPesquisarFuncMousePressed

    private void jRadioInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioInativarActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente Inativar este Funcionario??");
        if (resposta == JOptionPane.YES_OPTION) {
            if (jRadioInativar.isSelected()) {
                situacao = "Inativo";
                InativarFuncionario();
                JOptionPane.showMessageDialog(null, "Funcionário Inativado com sucesso!!", "Salvo", 1, new ImageIcon("imagens/ok.png"));
                limparCampos();
                jRadioInativar.setEnabled(false);
                //modelo.setNumRows(0);
                jButtonEditar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jRadioInativarActionPerformed

    private void txtNomeFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFuncKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cbCargo.requestFocus();
        }
    }//GEN-LAST:event_txtNomeFuncKeyPressed

    private void cbCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCargoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if(jButtonCadastrar.isEnabled()){
                jButtonCadastrar.requestFocus();
            }else{
                jButtonEditar.requestFocus();
            }
        }
    }//GEN-LAST:event_cbCargoKeyPressed

    private void jButtonCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCadastrarKeyPressed
        popularFuncionarioModelo();
        FuncC.verificardados(FuncB);
        limparCampos();
        jtPesquisarFunc.setEnabled(true);
        jButtonCadastrar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        txtNomeFunc.setText("");
        txtDataCad.setText("");
        habilitarCampos(false);
        //modelo.setNumRows(0);
        //FuncC.controlePesquisa(jtPesquisarFunc.getText(), modelo);
        jtPesquisarFunc.requestFocus();
    }//GEN-LAST:event_jButtonCadastrarKeyPressed

    private void jtPesquisarFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarFuncKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jtPesquisarFunc.getText().equals("")) {
                jButtonNovo.requestFocus();
            } else {
                preencherTabela(jtPesquisarFunc.getText());
                
            }
        }
    }//GEN-LAST:event_jtPesquisarFuncKeyPressed

    private void jButtonNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNovoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                String sql = "select * from usuario where loginUsu like '" + LoginTela.txtUsuario.getText() + "'";
                PreparedStatement pst = Conexao.getConnection().prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    if (rs.getString("permissaoUsu").equals("Administrador") || (rs.getString("permissaoUsu").equals("Operador"))) {
                        limparCampos();
                        habilitarCampos(true);
                        FuncC.ControleCodigo();
                        DataAtual = new Date();
                        txtDataCad.setText(FormatoData.format(DataAtual));
                        txtCodFunc.setText(FuncC.ControleCodigo());
                        jButtonNovo.setEnabled(false);
                        jRadioInativar.setEnabled(true);
                        txtNomeFunc.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Você não tem permissão para esta Funcionalidade!!\n Contate o administrador do sistema!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            }

        }
    }//GEN-LAST:event_jButtonNovoKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelCadCli;
    private javax.swing.JRadioButton jRadioInativar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableFuncionario;
    private javax.swing.JTextField jtPesquisarFunc;
    private javax.swing.JTextField txtCodFunc;
    private javax.swing.JFormattedTextField txtDataCad;
    private javax.swing.JTextField txtNomeFunc;
    // End of variables declaration//GEN-END:variables

    final void habilitarCampos(boolean valor) {
        txtCodFunc.setEnabled(valor);
        txtNomeFunc.setEnabled(valor);
        cbCargo.setEnabled(valor);
        txtDataCad.setEnabled(valor);
        jButtonCadastrar.setEnabled(valor);
        jButtonExcluir.setEnabled(valor);

    }

    final void popularFuncionarioModelo() {
        FuncB.setNome(txtNomeFunc.getText());
        FuncB.setFuncao(cbCargo.getSelectedItem().toString());
        FuncB.setDataCadastro(txtDataCad.getText());
    }

    final void limparCampos() {
        txtCodFunc.setText("");
        txtNomeFunc.setText("");
        cbCargo.setSelectedIndex(0);
        txtDataCad.setText("");
        //modelo.setNumRows(0);
        jtPesquisarFunc.setText("");
    }

    public void InativarFuncionario() {
        try {

            String SQLInsertion = "update funcionario set nomeFunc = ?, dtCadFunc = ?, funcaoFunc = ?,situacaoFunc = ?  where codFunc = ?";
            PreparedStatement pst = Conexao.getConnection().prepareStatement(SQLInsertion);
            pst.setString(1, txtNomeFunc.getText());
            pst.setString(2, txtDataCad.getText());
            pst.setString(3, cbCargo.getSelectedItem().toString());
            pst.setString(4, situacao);
            pst.setInt(5, Integer.parseInt(txtCodFunc.getText().toString()));

            pst.execute();
            Conexao.getConnection().commit();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            //JOptionPane.showMessageDialog(null, "Erro ao Alterar dados do entregador!!", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
    }

    public void preencherTabela(String pesquisa) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome", "Função", "Data Cadastro"};

        //String SQL = "select * from funcionario where nomeFunc like '%" + pesquisa + "%' and situacaoFunc like 'Ativo' order by nomeFunc";
        try {
            PreparedStatement pst = Conexao.getConnection().prepareStatement(pesquisa);
            ResultSet rs = pst.executeQuery();
            rs.next();
            do {
                dados.add(new Object[]{rs.getInt("codFunc"), rs.getString("nomeFunc"), rs.getString("funcaoFunc"), (Corretores.ConverterParaJava(rs.getString("dtCadFunc")))});
            } while (rs.next());

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, ex, "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            JOptionPane.showMessageDialog(null, "Erro ao preencher Tabela", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableFuncionario.setModel(modelo);
        jTableFuncionario.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFuncionario.getColumnModel().getColumn(0).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableFuncionario.getColumnModel().getColumn(1).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableFuncionario.getColumnModel().getColumn(2).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(3).setPreferredWidth(135);
        jTableFuncionario.getColumnModel().getColumn(3).setResizable(false);
        jTableFuncionario.getTableHeader().setReorderingAllowed(false);
        jTableFuncionario.setAutoResizeMode(jTableFuncionario.AUTO_RESIZE_OFF);
        jTableFuncionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
}
