/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelo.PedidoModelo;
import Controle.TelaPedidosControle;
import Utilitarios.Conexao;
import Utilitarios.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bokao
 */
public class TelaPedidos extends javax.swing.JFrame {

    TelaPedidosControle telaPedidoC;
    DefaultTableModel modelo;
    List<String> Lista;
    PedidoModelo PedidoB;

    public TelaPedidos() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Lista = new ArrayList<>();
        telaPedidoC = new TelaPedidosControle();
        modelo = (DefaultTableModel) tabelaPedidos.getModel();
        PedidoB = new PedidoModelo();

        modelo.setNumRows(0);
        telaPedidoC.ControlePesquisa(modelo);

        //preencherTabela("SELECT cliente.endCli, cliente.numeroEnd, pedido.codCliPed, pedido.horaPed, pedido.totalPed,pedido.statusPed, pedido.nomeMotoboy from cliente INNER JOIN pedido ON pedido.codCliPed = cliente.codCli");
        telaPedidoC.ControlePreencherComboboxMotoboy(Lista);
        for (String i : Lista) {
            cbMotoboy.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonFazendo = new javax.swing.JRadioButton();
        jRadioButtonPronto = new javax.swing.JRadioButton();
        jRadioButtonEntregue = new javax.swing.JRadioButton();
        jRadioButtonSaiuEntrega = new javax.swing.JRadioButton();
        jRadioButtonFinalizado = new javax.swing.JRadioButton();
        cbMotoboy = new javax.swing.JComboBox<>();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonAlterarStatus = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Pedidos Abertos");

        tabelaPedidos.setBackground(new java.awt.Color(204, 255, 204));
        tabelaPedidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaPedidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Pedido", "Endereço", "Número", "Hora Pedido", "Total", "Status", "Motoboy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPedidos.setRowHeight(30);
        jScrollPane1.setViewportView(tabelaPedidos);

        buttonGroup1.add(jRadioButtonFazendo);
        jRadioButtonFazendo.setText("fazendo");
        jRadioButtonFazendo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(jRadioButtonPronto);
        jRadioButtonPronto.setText("Pronto");
        jRadioButtonPronto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(jRadioButtonEntregue);
        jRadioButtonEntregue.setText("Entregue na mesa");
        jRadioButtonEntregue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(jRadioButtonSaiuEntrega);
        jRadioButtonSaiuEntrega.setText("Saiu para Entrega");
        jRadioButtonSaiuEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaiuEntregaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFinalizado);
        jRadioButtonFinalizado.setText("Finalizado");

        cbMotoboy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMotoboyMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbMotoboyMouseReleased(evt);
            }
        });
        cbMotoboy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbMotoboyKeyPressed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonAlterarStatus.setText("Alterar Status");
        jButtonAlterarStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jRadioButtonFazendo)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonPronto)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonEntregue)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSaiuEntrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonFinalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMotoboy, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterarStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizar)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFazendo)
                    .addComponent(jRadioButtonPronto)
                    .addComponent(jRadioButtonEntregue)
                    .addComponent(jRadioButtonSaiuEntrega)
                    .addComponent(jRadioButtonFinalizado)
                    .addComponent(cbMotoboy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonAlterarStatus))
                .addContainerGap())
        );

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ico_logout.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jButtonSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSairKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Tela de pedidos");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(961, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarStatusActionPerformed
        int linhaSelecionada = tabelaPedidos.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela antes de clicar no botão alterar!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            // Obtem o modelo da JTable
            tabelaPedidos.setValueAt(retornarStatusSelecionado(), linhaSelecionada, 5);
            tabelaPedidos.setValueAt(cbMotoboy.getSelectedItem().toString(), linhaSelecionada, 6);

            cbMotoboy.requestFocus();

        }
    }//GEN-LAST:event_jButtonAlterarStatusActionPerformed

    private void jRadioButtonSaiuEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaiuEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaiuEntregaActionPerformed

    private void cbMotoboyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMotoboyMouseClicked
        /*int linhaSelecionada = tabelaPedidos.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela antes de clicar no botão alterar!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            // Obtem o modelo da JTable
            tabelaPedidos.setValueAt(cbMotoboy.getSelectedItem().toString(), linhaSelecionada,5);
            jButtonSair.requestFocus();
        }*/
    }//GEN-LAST:event_cbMotoboyMouseClicked

    private void cbMotoboyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMotoboyMouseReleased

    }//GEN-LAST:event_cbMotoboyMouseReleased

    private void cbMotoboyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbMotoboyKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            int linhaSelecionada = tabelaPedidos.getSelectedRow();
            // Verificamos se existe realmente alguma linha selecionada
            if (linhaSelecionada < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um produto na tabela antes de clicar no botão alterar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                // Obtem o modelo da JTable
                tabelaPedidos.setValueAt(cbMotoboy.getSelectedItem().toString(), linhaSelecionada, 5);
                jButtonSair.requestFocus();
            }
        }
    }//GEN-LAST:event_cbMotoboyKeyPressed

    private void jButtonSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSairKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_jButtonSairKeyPressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        int ls = tabelaPedidos.getSelectedRow();
        if (cbMotoboy.getSelectedItem().equals("Selecione um motoboy")) {
            JOptionPane.showMessageDialog(null, "Selecione um motoboy", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));

        } else {
            populaModelo();
            telaPedidoC.ControleAtualizarPedido(PedidoB);
            //preencherTabela("select * from pedido where statusPed != 'Finalizado' order by horaPed asc limit 17");
            modelo.setNumRows(0);
            telaPedidoC.ControlePesquisa(modelo);
        }


    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMotoboy;
    private javax.swing.JButton jButtonAlterarStatus;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonEntregue;
    private javax.swing.JRadioButton jRadioButtonFazendo;
    private javax.swing.JRadioButton jRadioButtonFinalizado;
    private javax.swing.JRadioButton jRadioButtonPronto;
    private javax.swing.JRadioButton jRadioButtonSaiuEntrega;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables

    private String retornarStatusSelecionado() {
        String situacao = "NULL";
        if (jRadioButtonFazendo.isSelected()) {
            situacao = "Fazendo";
        } else if (jRadioButtonPronto.isSelected()) {
            situacao = "Pronto";
        } else if (jRadioButtonEntregue.isSelected()) {
            situacao = "Entregue na mesa";
        } else if (jRadioButtonSaiuEntrega.isSelected()) {
            situacao = "Saiu Para Entrega";
        } else if (jRadioButtonFinalizado.isSelected()) {
            situacao = "Finalizado";
        }
        return situacao;
    }

    /*public void populaModelo(){
        int ls = tabelaPedidos.getSelectedRow();
        PedidoB.setCodPedido(Integer.parseInt(tabelaPedidos.getValueAt(ls, 0).toString()));
        PedidoB.setStatusPed(tabelaPedidos.getValueAt(ls, 2).toString());
        PedidoB.setNomeMotoboy(tabelaPedidos.getValueAt(ls, 3).toString());
        //PedidoB.setCodEntrPedido(Integer.parseInt(cbMotoboy.getSelectedItem().toString()));
        //PedidoB.setStatusPed(tabelaPedidos.getValueAt(ls, 4).toString());
    }*/
    public void populaModelo() {
        int ls = tabelaPedidos.getSelectedRow();
        PedidoB.setCodPedido(Integer.parseInt(tabelaPedidos.getValueAt(ls, 0).toString()));
        PedidoB.setStatusPed(retornarStatusSelecionado());
        PedidoB.setNomeMotoboy(cbMotoboy.getSelectedItem().toString());

    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código Pedido", "endereço", "Número", "Hora Pedido", "Status", "Motoboy"};

        //String SQL = "select * from cliente where nomeCli like '%" + jtNomeCli.getText() + "%' and situacao like 'Ativo' order by endCli";
        try {
            PreparedStatement pst = Conexao.getConnection().prepareStatement(SQL);
            ResultSet rs = pst.executeQuery();
            rs.next();
            do {
                dados.add(new Object[]{rs.getInt("codCliPed"), rs.getString("endCli"), rs.getString("numeroEnd"), rs.getDate("horaPed"), rs.getString("statusPed"), rs.getString("nomeMotoboy")});
            } while (rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
            //JOptionPane.showMessageDialog(null, "Erro ao preencher Tabela", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabelaPedidos.setModel(modelo);
        tabelaPedidos.getColumnModel().getColumn(0).setPreferredWidth(110);
        tabelaPedidos.getColumnModel().getColumn(0).setResizable(false);
        tabelaPedidos.getColumnModel().getColumn(1).setPreferredWidth(550);
        tabelaPedidos.getColumnModel().getColumn(1).setResizable(false);
        tabelaPedidos.getColumnModel().getColumn(2).setPreferredWidth(90);
        tabelaPedidos.getColumnModel().getColumn(2).setResizable(false);
        tabelaPedidos.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabelaPedidos.getColumnModel().getColumn(3).setResizable(false);
        tabelaPedidos.getColumnModel().getColumn(4).setPreferredWidth(160);
        tabelaPedidos.getColumnModel().getColumn(4).setResizable(false);
        tabelaPedidos.getColumnModel().getColumn(5).setPreferredWidth(270);
        tabelaPedidos.getColumnModel().getColumn(5).setResizable(false);
        tabelaPedidos.getTableHeader().setReorderingAllowed(false);
        tabelaPedidos.setAutoResizeMode(tabelaPedidos.AUTO_RESIZE_OFF);
        tabelaPedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

}
